name: Hourly Data & Prediction

on:
  schedule:
    - cron: '*/30 * * * *'   # tiap jam UTC (WIB = UTC+7)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate data & prediction
        run: python scripts/fetch_predict.py

      - name: Commit & push if changed (as fbrianzy)
        run: |
          git config user.name "fbrianzy"
          git config user.email "bagusfeb60@gmail.com"
          if ! git diff --quiet; then
            git add data/*.json
            git commit -m "Hourly update by fbrianzy: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit."
          fi
